[package]
name = "devicon-lookup"
description = "Prepend the correct devicon to the beginning of each filename"
version = "0.4.0"
authors = ["Corey Alexander <coreyja@gmail.com>"]
repository = "https://github.com/coreyja/devicon-lookup"
license = "MIT"

[dependencies]
lazy_static = "1.2.0"

[dev-dependencies]
assert_cmd = "0.6.0"
