pre-release-commit-message = "Release {{version}} ðŸŽ‰ðŸŽ‰"
pre-release-replacements = [ {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"}, {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"} ]
sign-commit = true
sign-tag = true
